"""add methodology to student

Revision ID: 2c4a1533e811
Revises: cfbcb50369f1
Create Date: 2026-08-24 12:54:05.865678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import gpt_teacher_db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c4a1533e811'
down_revision: Union[str, None] = 'cfbcb50369f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SOCRATIC', 'DIRECT', 'STEP_BY_STEP', name='teachingmethodology', schema='gpt_teacher').create(op.get_bind())
    op.add_column(
        'student',
        sa.Column(
            'methodology',
            postgresql.ENUM('SOCRATIC', 'DIRECT', 'STEP_BY_STEP', name='teachingmethodology', schema='gpt_teacher', create_type=False),
            nullable=False,
            server_default='STEP_BY_STEP',
        ),
        schema='gpt_teacher',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'methodology', schema='gpt_teacher')
    sa.Enum('SOCRATIC', 'DIRECT', 'STEP_BY_STEP', name='teachingmethodology', schema='gpt_teacher').drop(op.get_bind())
    # ### end Alembic commands ###