"""fix name password_hash

Revision ID: c22a273ef977
Revises: e5aa504ee92f
Create Date: 2026-01-08 00:12:06.098402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import gpt_teacher_db


# revision identifiers, used by Alembic.
revision: str = 'c22a273ef977'
down_revision: Union[str, None] = 'e5aa504ee92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False), schema='gpt_teacher')
    op.drop_column('student', 'password_hash', schema='gpt_teacher')
    op.add_column('teacher', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False), schema='gpt_teacher')
    op.drop_column('teacher', 'password_hash', schema='gpt_teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='gpt_teacher')
    op.drop_column('teacher', 'hashed_password', schema='gpt_teacher')
    op.add_column('student', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='gpt_teacher')
    op.drop_column('student', 'hashed_password', schema='gpt_teacher')
    # ### end Alembic commands ###
