"""add category to problem

Revision ID: cfbcb50369f1
Revises: c22a273ef977
Create Date: 2026-07-25 10:09:50.169560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import gpt_teacher_db


# revision identifiers, used by Alembic.
revision: str = 'cfbcb50369f1'
down_revision: Union[str, None] = 'c22a273ef977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('category', sa.String(length=100), nullable=True), schema='gpt_teacher')
    op.create_index(op.f('ix_problem_category'), 'problem', ['category'], unique=False, schema='gpt_teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_category'), table_name='problem', schema='gpt_teacher')
    op.drop_column('problem', 'category', schema='gpt_teacher')
    # ### end Alembic commands ###
