"""move methodology from student to classroom_student

Revision ID: dbb6beac4e58
Revises: 2c4a1533e811
Create Date: 2026-09-11 22:15:38.648136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import gpt_teacher_db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbb6beac4e58'
down_revision: Union[str, None] = '2c4a1533e811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'classroom_student',
        sa.Column(
            'methodology',
            postgresql.ENUM('SOCRATIC', 'DIRECT', 'STEP_BY_STEP', name='teachingmethodology', schema='gpt_teacher', create_type=False),
            nullable=False,
            server_default=sa.text("'SOCRATIC'::gpt_teacher.teachingmethodology"),
        ),
        schema='gpt_teacher',
    )
    op.drop_column('student', 'methodology', schema='gpt_teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('methodology', postgresql.ENUM('SOCRATIC', 'DIRECT', 'STEP_BY_STEP', name='teachingmethodology', schema='gpt_teacher', create_type=False), server_default=sa.text("'STEP_BY_STEP'::gpt_teacher.teachingmethodology"), autoincrement=False, nullable=False), schema='gpt_teacher')
    op.drop_column('classroom_student', 'methodology', schema='gpt_teacher')
    # ### end Alembic commands ###