"""bootstrap db

Revision ID: e5aa504ee92f
Revises: 
Create Date: 2026-01-07 23:41:03.520822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import gpt_teacher_db
from gpt_teacher_db.gpt_teacher import ConsolidatedData
from gpt_teacher_db.gpt_teacher.core.base_model_json_conversor import PydanticJSONType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5aa504ee92f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'AI', name='messagetype', schema='gpt_teacher').create(op.get_bind())
    sa.Enum('OPEN', 'CLOSED', name='sessionstatus', schema='gpt_teacher').create(op.get_bind())
    op.create_table('student',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('student_pkey')),
    schema='gpt_teacher'
    )
    op.create_table('teacher',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('teacher_pkey')),
    schema='gpt_teacher'
    )
    op.create_table('classroom',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['gpt_teacher.teacher.id'], name=op.f('classroom_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('classroom_pkey')),
    schema='gpt_teacher'
    )
    op.create_index(op.f('ix_classroom_teacher_id'), 'classroom', ['teacher_id'], unique=False, schema='gpt_teacher')
    op.create_table('classroom_student',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['gpt_teacher.classroom.id'], name=op.f('classroom_student_classroom_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['gpt_teacher.student.id'], name=op.f('classroom_student_student_id_fkey')),
    sa.PrimaryKeyConstraint('classroom_id', 'student_id', name=op.f('classroom_student_pkey')),
    schema='gpt_teacher'
    )
    op.create_table('problem',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_student_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['gpt_teacher.classroom.id'], name=op.f('problem_classroom_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_student_id'], ['gpt_teacher.student.id'], name=op.f('problem_created_by_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('problem_pkey')),
    schema='gpt_teacher'
    )
    op.create_index(op.f('ix_problem_classroom_id'), 'problem', ['classroom_id'], unique=False, schema='gpt_teacher')
    op.create_table('student_session',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', name='sessionstatus', schema='gpt_teacher', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['gpt_teacher.problem.id'], name=op.f('student_session_problem_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['gpt_teacher.student.id'], name=op.f('student_session_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_session_pkey')),
    schema='gpt_teacher'
    )
    op.create_index(op.f('ix_student_session_problem_id'), 'student_session', ['problem_id'], unique=False, schema='gpt_teacher')
    op.create_index(op.f('ix_student_session_status'), 'student_session', ['status'], unique=False, schema='gpt_teacher')
    op.create_index(op.f('ix_student_session_student_id'), 'student_session', ['student_id'], unique=False, schema='gpt_teacher')
    op.create_table('chat_message',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('type', postgresql.ENUM('USER', 'AI', name='messagetype', schema='gpt_teacher', create_type=False), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('code_review', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['gpt_teacher.problem.id'], name=op.f('chat_message_problem_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['gpt_teacher.student_session.id'], name=op.f('chat_message_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_pkey')),
    schema='gpt_teacher'
    )
    op.create_index(op.f('ix_chat_message_problem_id'), 'chat_message', ['problem_id'], unique=False, schema='gpt_teacher')
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False, schema='gpt_teacher')
    op.create_index(op.f('ix_chat_message_type'), 'chat_message', ['type'], unique=False, schema='gpt_teacher')
    op.create_table('consolidated',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('data', PydanticJSONType(ConsolidatedData), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['gpt_teacher.student_session.id'], name=op.f('consolidated_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consolidated_pkey')),
    schema='gpt_teacher'
    )
    op.create_index(op.f('ix_consolidated_session_id'), 'consolidated', ['session_id'], unique=True, schema='gpt_teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consolidated_session_id'), table_name='consolidated', schema='gpt_teacher')
    op.drop_table('consolidated', schema='gpt_teacher')
    op.drop_index(op.f('ix_chat_message_type'), table_name='chat_message', schema='gpt_teacher')
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message', schema='gpt_teacher')
    op.drop_index(op.f('ix_chat_message_problem_id'), table_name='chat_message', schema='gpt_teacher')
    op.drop_table('chat_message', schema='gpt_teacher')
    op.drop_index(op.f('ix_student_session_student_id'), table_name='student_session', schema='gpt_teacher')
    op.drop_index(op.f('ix_student_session_status'), table_name='student_session', schema='gpt_teacher')
    op.drop_index(op.f('ix_student_session_problem_id'), table_name='student_session', schema='gpt_teacher')
    op.drop_table('student_session', schema='gpt_teacher')
    op.drop_index(op.f('ix_problem_classroom_id'), table_name='problem', schema='gpt_teacher')
    op.drop_table('problem', schema='gpt_teacher')
    op.drop_table('classroom_student', schema='gpt_teacher')
    op.drop_index(op.f('ix_classroom_teacher_id'), table_name='classroom', schema='gpt_teacher')
    op.drop_table('classroom', schema='gpt_teacher')
    op.drop_table('teacher', schema='gpt_teacher')
    op.drop_table('student', schema='gpt_teacher')
    sa.Enum('OPEN', 'CLOSED', name='sessionstatus', schema='gpt_teacher').drop(op.get_bind())
    sa.Enum('USER', 'AI', name='messagetype', schema='gpt_teacher').drop(op.get_bind())
    # ### end Alembic commands ###
